server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0     # Redis数据库索引 （默认为0）
    port: 6379      # Redis服务器连接端口
    password:       # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8    # 连接池最大连接数（负值没有限制）
        max-wait: -1     # 连接池最大阻塞等待时间（负值表示没有限制）
        max-idle: 8      # 连接池中最大空连接数
        min-idle: 0      # 连接池中最小空连接数
    timeout: 3000ms      # 连接超世时间
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mall-port

  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
    #   确认消息已经发送到交换机选择确认类型为交互
    publisher-confirm-type: correlated

mybatis:
  mapper-locations:
    - classparh:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization
  tokenHead: Bearer
  secret: mySecret
  expiration: 604800

redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120

data:
  elasticsearch:
    repositories:
      enabled: true
    cluster-nodes: 127.0.0.1:9300
    cluster-name: elasticsearch
